const TOOL_RECTANGLE = 'TOOL_RECTANGLE';
const TOOL_ARROW     = 'TOOL_ARROW';
const TOOL_ERASER    = 'TOOL_ERASER';

const RECT_FILL    = 'RECT_FILL';
const RECT_OUTLINE = 'RECT_OUTLINE';


module.exports = { TOOL_RECTANGLE, TOOL_ARROW, TOOL_ERASER, RECT_FILL, RECT_OUTLINE };
