const TOOL_RECTANGLE = 'TOOL_RECTANGLE';
const TOOL_ARROW     = 'TOOL_ARROW';

const RECT_FILL  = 'RECT_FILL';
const RECT_EMPTY = 'RECT_EMPTY';


module.exports = { TOOL_RECTANGLE, TOOL_ARROW, RECT_FILL, RECT_EMPTY };
