const POPUP_OK        = 0;
const POPUP_OK_CANCEL = 1;

const GUI_TEXTBOX = 0;
const GUI_NUMBER  = 1;
const GUI_INTEGER = 2;


export { POPUP_OK, POPUP_OK_CANCEL, GUI_TEXTBOX, GUI_NUMBER, GUI_INTEGER };
