const GUI_DEFAULT_MAX_LEN = 75;
const GUI_DEFAULT_WIDTH   = '8vw';

const GUI_TEXTBOX    = 0;
const GUI_NUMBER     = 1;
const GUI_INTEGER    = 2;
const GUI_SIGNED_INT = 3;


export
{
	GUI_DEFAULT_MAX_LEN,
	GUI_DEFAULT_WIDTH,

	GUI_TEXTBOX,
	GUI_NUMBER,
	GUI_INTEGER,
	GUI_SIGNED_INT
};
